### ISSUE TITLE
heapstats-attacher shell script can not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by ismlsmile** [HeapStats/heapstats#123]
The error is:
./heapstats-attacher: 26: ./heapstats-attacher: Syntax error: "(" unexpected

The script can not run on dash, and should run on bash. So the first line should change from:
#!/bin/sh
to:
#! /bin/bash

**Comment by ykubota** [comment]
Thank you for your reporting!
We fixed to run on Ubuntu 16.04 by #124 

If there is still problem, please reopen :)
