### ISSUE TITLE
Analyzer 2.1.0 : "Data Format : HeapSize/Instance" radio button does not work

### ISSUE THREAD

**Issue by stakao** [HeapStats/heapstats#135]
In HeapStats 2.1.0 pre-release test, I found that the radio button does not work.

The radio button are located above the sub menu tabs (see the figure below).
![analyzer-no6](https://user-images.githubusercontent.com/13461794/36524165-55c84ea4-17e8-11e8-9945-ad673c57f7db.JPG)

It is expected that if you select the "HeapSize", the graphs on screens indicate heap size (usage).
However, the graphs do not change.

**Comment by ykubota** [comment]
HeapStats analyzer 2.1.0 pre-release requires pushing [OK] button at the top right to change data format as below figure.

![image](https://user-images.githubusercontent.com/489607/36524970-7088e5fc-17eb-11e8-84dc-6d02818e2d95.png)

Please re-check your test and close this issue if you can change data format.

**Comment by stakao** [comment]
I understand. I can change the graphs in my test, so I will close this issue.
