### ISSUE TITLE
Building agent on Mac OS X

### ISSUE THREAD

**Issue by jumarko** [HeapStats/heapstats#147]
I'm wondering if there's any hope in trying to build the agent on Mac OS X (10.14.6).
Is the agent build only supported for Linux?
I tried to build from the source but got the error _**C compiler cannot make executables**_ after running _**./configure**_
```
(my-env)➜  heapstats git:(master) ./configure --with-jdk=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/jumar/workspace/java/heapstats':
configure: error: C compiler cannot create executables
See `config.log' for more details

```

**Comment by ykubota** [comment]
Thank you for your report.

Unfortunately, no plan for support OSX because we don't have a test environment. Currently, HeapStats agent is support for Linux only.
Of course, your contributions are always welcome :)

**Comment by jumarko** [comment]
At least thanks a lot for the fast response! :)

**Comment by ykubota** [comment]
Let me close this issue, please feel free to reopen if have any contributions/questions :)
