### ISSUE TITLE
Bug 3003: Use macro in heapstats.conf

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#30]
HeapStats user requests that user-defined value (macro) can use in heapstats.conf.
This request has been filed as [Bug 3003](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3003) .

Yuji suggested we can use [custom log format in Apache httpd](http://httpd.apache.org/docs/current/en/mod/mod_log_config.html#formats) .

I want to discuss about this in this issue and [Bugzilla](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3003) .

**Comment by YaSuenag** [comment]
I think we can implement as below:

```
var macro_val=/tmp

file=${macro_val}/snapshot.dat
```

**Comment by ykubota** [comment]
We should close this issue without fix by the following reasons

* we don't hear any requests about this enhancement from users
* we don't have any plan to add new options of heapstats.conf
* this change might impact existing users

Any thoughts?

**Comment by YaSuenag** [comment]
@ykubota I agree with you.
I also haven't heard any request from other users about this. So I close this as "Won't Fix".
