### ISSUE TITLE
heapstats-cli should check JAVA_HOME value

### ISSUE THREAD

**Issue by tokuhirom** [HeapStats/heapstats#44]
heapstats-cli command doesn't check $JAVA_HOME value, as a result if there's no JAVA_HOME environment variable, user may see following useless message:

```
/usr/bin/heapstats-cli: line 9: /bin/java: No such file or directory
```

**Comment by ykubota** [comment]
Thank you for your report!

I booked this issue at [bugzilla](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3214).
I will improve heapstats-cli to check JAVA_HOME .
