### ISSUE TITLE
Bug 3256: Some controls are overlapped when window is resized

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#53]
When I resized window size of HeapStats Analyzer, some controls are located incorrect position.
For example, `OK` button is overlapped on `Instance` radio button:

![analyzer](https://cloud.githubusercontent.com/assets/7421132/20873083/874aff26-bae7-11e6-948b-7923770aed36.png)

Currently, most of controls are located on [AnchorPane](https://docs.oracle.com/javase/jp/8/javafx/api/javafx/scene/layout/AnchorPane.html) with anchor position. I think we should use [VBox](https://docs.oracle.com/javase/jp/8/javafx/api/javafx/scene/layout/VBox.html) and [HBox](https://docs.oracle.com/javase/jp/8/javafx/api/javafx/scene/layout/HBox.html).

**Comment by YaSuenag** [comment]
I filed this to [IcedTea Bugzilla](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3256)

**Comment by ykubota** [comment]
Nice catch. Please upload a screenshot when you will fix this.

**Comment by YaSuenag** [comment]
This might be big changes.
So I change the miliestone to 2.1.

**Comment by YaSuenag** [comment]
I've pushed new commit for this issue.
This changes can avoid control overlap as below:

![github](https://cloud.githubusercontent.com/assets/7421132/21646474/b456fc0e-d2d9-11e6-8d11-f96ecf0262c2.png)
