### ISSUE TITLE
Bug 3259: [REFACTORING] color selection for chart classes

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#55]
Java Heap chart in SnapShot summary tab uses incorrect colors for drawing symbols as below:

![screenshot from 2016-12-06 12-55-40](https://cloud.githubusercontent.com/assets/7421132/20912546/52cd84d6-bbb3-11e6-8012-75956afc2306.png)

We should fix it to use same colors.

**Comment by YaSuenag** [comment]
I filed this issue to [IcedTea Bugzilla](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3259)

**Comment by YaSuenag** [comment]
I changed title of this bug because I found another bug for chart color selection.

The legend of System CPU chart on Resource Data tab is:
![before](https://cloud.githubusercontent.com/assets/7421132/20928612/0731c116-bc0a-11e6-8283-bef28ba8ff34.png)
`user` and `guest` is same color.
Correct color is:
![after](https://cloud.githubusercontent.com/assets/7421132/20928634/1f2ad410-bc0a-11e6-96ab-6522928b3b1a.png)

According to [JavaFX 9 source](http://hg.openjdk.java.net/openjfx/9-dev/rt/file/a64f5403de11/modules/javafx.controls/src/main/java/javafx/scene/chart/XYChart.java#l157), `default-color` selector is `0`-`7`. `8` and upper value cannot be used.

So I use `series<n>` selector for selecting chart series color.
It works fine.

Could you review it?

**Comment by ykubota** [comment]
Does this code available from JavaFX 9? Do we need to change requirements?

**Comment by YaSuenag** [comment]
@ykubota No.
OpenJFX 8 master has [same code](http://hg.openjdk.java.net/openjfx/8/master/rt/file/f89b7dc932af/modules/controls/src/main/java/javafx/scene/chart/XYChart.java#l151).

**Comment by ykubota** [comment]
@YaSuenag OK, then I  don't have any objections.
