### ISSUE TITLE
Chart symbol enhancement

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#65]
Currently, HeapStats Analyzer in trunk repos shows symbols on the chart as below:
![before](https://cloud.githubusercontent.com/assets/7421132/21182633/5d50df08-c247-11e6-8ed3-7ad82d657deb.png)
It is very useful for checking point of the data collection event. However, if point will be plot a lot, it might be ugly.

So I think we show the symbol around mouse pointer only like [Kibana](https://www.elastic.co/products/kibana) as below:
![after](https://cloud.githubusercontent.com/assets/7421132/21182639/6945ba40-c247-11e6-94dc-30d6a1c0918d.png)

What do you think about this change?
If it is acceptable, I will file it to [IcedTea Bugzilla](http://icedtea.classpath.org/bugzilla/) and start to work for it.

Also I think Archive Line (black vertical line) and Reboot Line (yellow vertical line) can be replaced to chart symbol. These symbols are shown always, and the shape of them is square.
I want to hear the opinion for it too.

**Comment by YaSuenag** [comment]
This commit is for SnapShot summary tab.
If this change is accepted, I will apply this enhancement to all panes which has chart(s) in HeapStats Analyzer.

**Comment by ykubota** [comment]
I think that these points (aka circles on the charts) are important information for checking overview because  HeapStats doesn't get runtime information at regular intervals.
If a user checks the snapshot which contains many major GCs, i.e., snapshot times, these points might be ugly as you say.

I think that we would be good to create a threshold as to how many the points does the loaded snapshot have, to change whether the points view or hide.

**Comment by YaSuenag** [comment]
> I think that we would be good to create a threshold as to how many the points does the loaded snapshot have, to change whether the points view or hide.

I think this (reduce max count of symbols on a chart) is a different enhancement.
It improves performance of renderar, so I want to work for this ASAP too.

Should we work for adding threshold for chart symbols at first?

**Comment by ykubota** [comment]
> I think this (reduce max count of symbols on a chart) is a different enhancement.

I think that the threshold is used to judging whether all the symbols will view or hide.

**Comment by YaSuenag** [comment]
@ykubota Do you want to say "threshold" means "threshold of the value"? - for example, Analyzer shows symbols which points that Java heap usage is 80% or higher.

I use "threshold" which means "max plot count" - for example, we should show 20 plots on a chart. So we have to calculate max value to plot (for reducing plots on a chart).

**Comment by ykubota** [comment]
@YaSuenag 
Apologies for the confusing.
Analyzer shows symbols when loads a snapshot which include no longer "30" major GCs.
I want to say that we should better to create a new "threshold" such as "30" of the above to prevent ugly and keep a useful overview.

**Comment by YaSuenag** [comment]
@ykubota Okay, could you file your comment to Bugzilla?
We will start to work for it at first.

**Comment by ykubota** [comment]
@YaSuenag Sure.

*(edited)*
here: http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3268

**Comment by YaSuenag** [comment]
Thanks @ykubota !
I suspend this work.

**Comment by ykubota** [comment]
We didn't hear any requests from users in the past year. So we had better to show the charts without sampling to read accurately.

If any user want to this enhancement, we reopen it.
