### ISSUE TITLE
Bug 3293: [REFACTORING] Realtime deadlock detector implementation

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#76]
This issue is for [Bug 3293: [REFACTORING] Realtime deadlock detector implementation](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3293).

[Bug 3285](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3285) (issue #73) reports current implementation of HeapStats deadlock detector might break thead state and safepoint state. It might be cause of assertion failure in HotSpot VM (at safepoint).

We have to refactor this feature to be more safely and fast.

I've some implementation examples to [my Gist](https://gist.github.com/YaSuenag/b8d92b209f0c808da630aca4fb9f8fe7). Could you check them?
IMHO, we should refactor to use `jmm_FindMonitorDeadlockedThreads()` because `deadlockDetector.cpp` in this Gist might be call many VMOps to get lock owner when many relevant threads are available.

After this discussion, I will work to integrate it to HeapStats Agent.

**Comment by ykubota** [comment]
Sorry for late reply. I investigated your suggestions. I think we would be better to choose the later suggestion to make low-overhead deadlock detector. And we should keep disable deadlock detector as default. 

Using standard APIs such as the former suggestion also is good, but I think that many developers can write it by themselves. I believe more low-overhead deadlock detector will be helpful tool for developers.

So we should refactor to use `jmm_FindMonitorDeadlockedThreads()`.

**Comment by YaSuenag** [comment]
I implemented new deadlock detector with `jmm_FindMonitorDeadlockedThreads()`, however it does not work because `MonitorContendedEnter` JVMTI event is called just before pushing to the waiters. So deadlock detector in HotSpot cannot detect the deadlock.

I'll try to implement another one.

**Comment by YaSuenag** [comment]
I pushed an new deadlock detector implementation.
This implementation uses two STL `map` :

1. `monitor_owners`
    * Map of owned monitor and owner thread.
    * Key: Hashcode of owned monitor object, Value: Hashcode of owner thread object.
2. `waiter_list`
    * Map of waiter thread and wanted monitor.
    * Key: Hashcode of waiter thread object, Value: Hashcode of wanted monitor object.

However, this implementation is incomplete. We should implement as below:

* Thread safe implementation
    * New two STL `map` should be protected with mutex or spin lock.
* Change structure of SNMP trap for deadlock
    * This implementation cannot calculate number of deadlock threads. So deadlock count in SNMP trap should be removed.

I will continue to work for them.

**Comment by YaSuenag** [comment]
I updated the implementation.
This commit realize thread-safe call and counting deadlock threads.

Please tell me if you have any comment.
If I do not hear any objection until 28 July JST, I will send PR.

**Comment by ykubota** [comment]
@YaSuenag 
I also thought a prototype of deadlock detector by jmm for finding something need to change your proposal. But, I did not find any comments about basic idea.  Please send PR!
