### ISSUE TITLE
Migrate to Intel TBB

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/heapstats#97]
For ease of maintainance, I want to migrate each containers to them in [Intel TBB](https://www.threadingbuildingblocks.org/) .

Currently, we use C++11 `unordered_map` . However it is supported since [TBB 4.2](https://software.intel.com/en-us/articles/whats-new-intel-threading-building-blocks-42) . So we have to use `concurrent_hash_map` and `concurrent_queue` for CentOS 6 / RHEL 6 because their TBB version is too old ! (2.2)

**Comment by YaSuenag** [comment]
I want to resume the discussion about this issue.

I've pushed [tbb branch](https://github.com/HeapStats/heapstats/tree/tbb) for this issue.
This change works fine on Fedora 25 / CentOS 6.5 / Raspbian Jessie on Raspberry Pi 2.

To apply this change, we need to stop the support for CentOS 5 / RHEL 5 because these C++ compiler (GCC) is too old.
So I want to discuss about the following:

1. Can we stop the support for CentOS 5 / RHEL 5 ?
    * If user can use GCC 4.4 or later on these platforms, HeapStats agent can work on it.
2. Can we stop the support for Raspberry Pi 1 ?
    * If user can compile TBB for ARMv5 (Raspberry Pi 1), HeapStats agent can work on it.
3. Can we use [Intel TBB](https://www.threadingbuildingblocks.org/) in HeapStats Agent ?

**Comment by YaSuenag** [comment]
I will file this issue to [IcedTea Bugzilla](http://icedtea.classpath.org/bugzilla/) and will send PR after the discussion.

**Comment by YaSuenag** [comment]
@ykubota agreed plan 1. (drop CentOS 5 / RHEL 5 support) and 2. (drop Raspberry Pi 1 support).
He will measure performance of tbb branch. We continue to discuss about this issue.

http://icedtea.classpath.org/pipermail/heapstats/2017-June/002105.html

**Comment by ykubota** [comment]
@YaSuenag I got several crashes when I ran SPECjvm2008 with heapstats (`tbb` branch).

An example crash log is [here](https://gist.github.com/ykubota/70bfd6121e6258c276bce661ac854c31)

**Comment by YaSuenag** [comment]
@ykubota Thank you for your report!
I guess this crash is caused by class unloading.

`TSnapShotContainer::removeObjectData()` pops `TObjectData` in `unloadedList`. But this list should not be pop'ed at this point because this list is scaned another `removeObjectData` call for other `TSnapShotContainer` instance and for `TClassContainer` in `OnGarbageCollectionFinishForUnload()`.

I've fixed this issue.
Could you try current tbb branch again?

**Comment by ykubota** [comment]
@YaSuenag 
Thanks for fixing.

Unfortunately, I got crash by [avx codes](https://github.com/HeapStats/heapstats/blob/8478927/agent/src/heapstats-engines/arch/x86/avx/snapShotContainer.inline.hpp#L83) when I ran SPECjvm2008 to test a73e611 .
Crash log is available [here](https://gist.github.com/ykubota/b4ec77cbecd1b99f1c1431ab4768cf5a)

**Comment by YaSuenag** [comment]
@ykubota Thank you for your report!
I guess this crash related to `TClassCounter`, so I fixed related code.

**Comment by ykubota** [comment]
There are not any performance issues therefore we can push `tbb` branch to `master`.

I ran SPECjvm2008 benchmark under the following conditions to compare performance of `tbb` which merged `master` (72303bc), `master` (db8d6ef) and no-HeapStats.

 * java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4
 * kernel-3.10.0-514.el7.x86_64
 * glibc-2.17-196.el7.x86_64

And all cases showed very low execution overhead as below table.

| | | w/o TRecorder | w/ TRecorder
-- | -- | -- | --
OH (tbb v.s. master) | CMS | 0.99% | 0.69%
  | G1 | 0.01% | 0.43%
  | Parallel | -0.06% | 0.73%
OH (tbb v.s. no-HeapStats) | CMS | 0.31% | 0.03%
  | G1 | -0.24% | -0.10%
  | Parallel | 0.11% | -0.23%

Detailed SPECjvm2008 benchmark scores is the following. The scores are average of 5 executions.

* Thread-Recorder disabled

Cases | GC | Composite Result | complier | compress | crypto | derby | mpegaudio | scimark.large | scimark.small | serial | xml
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
tbb | CMS | 306.2304278 | 705.326 | 266.222 | 299.054 | 599.108 | 188.68 | 84.864 | 377.666 | 193.292 | 602.248
| |G1 | 314.068925 | 858.59 | 265.896 | 297.336 | 615.174 | 192.414 | 87.28 | 380.294 | 195.922 | 569.02
| | Parallel | 311.7425931 | 804.776 | 265.652 | 302.27 | 623.606 | 191.222 | 81.772 | 382.02 | 183.308 | 630.176
master | CMS | 309.298569 | 706.6766667 | 266.49 | 305.53 | 595.9833333 | 192.7233333 | 85.8 | 380.77 | 195.2066667 | 614.6567
| |G1 | 314.1093469 | 860.0466667 | 264.2466667 | 295.8466667 | 614.1533333 | 190.9633333 | 87.37 | 383.29 | 197.2833333 | 571.3767
| |Parallel | 311.5483914 | 798.56 | 261.7033333 | 303.1466667 | 617.7333333 | 189.74 | 81.25333333 | 373.4666667 | 195.26 | 628.4833
No-HeapStats | CMS | 307.1783043 | 718.81 | 266.124 | 304.318 | 600.468 | 191.84 | 85.05 | 377.906 | 192.336 | 587.41
| |G1 | 313.325035 | 862.52 | 267.106 | 296.012 | 619.244 | 191.866 | 86.97 | 379.658 | 193.234 | 562.974
| |Parallel | 312.0860585 | 814.3475 | 266.225 | 302.77 | 613.3575 | 191.985 | 81.2775 | 378.025 | 187.0175 | 632.33

* Thread-Recorder enabled

Case | GC | Composite Result | complier | compress | crypto | derby | mpegaudio | scimark.large | scimark.small | serial | xml
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
tbb | CMS | 307.0988757 | 708.966 | 265.96 | 302.132 | 592.872 | 191.438 | 84.948 | 377.078 | 193.304 | 606.808
| | G1 | 313.6353516 | 855.378 | 266.54 | 298.876 | 612.93 | 191.014 | 87.282 | 379.836 | 194.45 | 570.964
| | Parallel | 312.8163634 | 795.124 | 265.532 | 304.96 | 617.46 | 191.892 | 81.52 | 378.422 | 191.706 | 635.724
master | CMS | 309.2384391 | 707.052 | 266.134 | 303.532 | 598.228 | 192.69 | 85.758 | 380.828 | 195.97 | 613.714
| | G1 | 315.002805 | 859.55 | 266.676 | 303.018 | 620.538 | 191.936 | 87.384 | 379.072 | 195.004 | 571.458
| | Parallel | 315.1153793 | 809.62 | 266.066 | 304.51 | 624.01 | 192.648 | 81.132 | 379.746 | 197.752 | 637.664
No-HeapStats | CMS | 307.1783043 | 718.81 | 266.124 | 304.318 | 600.468 | 191.84 | 85.05 | 377.906 | 192.336 | 587.41
| | G1 | 313.325035 | 862.52 | 267.106 | 296.012 | 619.244 | 191.866 | 86.97 | 379.658 | 193.234 | 562.974
| | Parallel | 312.0860585 | 814.3475 | 266.225 | 302.77 | 613.3575 | 191.985 | 81.2775 | 378.025 | 187.0175 | 632.33

**Comment by YaSuenag** [comment]
Thank you so much! Yuji.

I addressed this enhancement to IcedTea Bugzilla as [Bug 3511](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3511) and have opened new PR #128 .
